### PR TITLE
fix bad `text` values in `parse`

### LINKED ISSUE #100: parse is swallowing literal characters preceding dot (.) when pattern contains a brace expression
If the pattern has literal characters before a dot (.), and a brace expression after the dot, the parse function swallows the literal characters that precede the dot.

Consider the following example:

```js
require('picomatch').makeRe('1.{0..9}')
```

Here's what we expect to see:

```
/^(?:1\.[0-9])$/
```

However, what we see instead is:

```
/^(?:.[0-9])$/
```

Notice that not only is the `1` missing, the dot is not escaped.

We can find evidence of this problem by inspecting the output of `parse`.

```js
{
  input: '1.{0..9}',
  consumed: '1.{0.9}',
  output: '.[0-9]',
  ...
}
```

The workaround for this behavior is to enclose the literal characters in a pair of round brackets.

```js
require('picomatch').makeRe('(1).{0..9}')
```

Aside from the additional group, we now get the output we expect from the earlier pattern:

```
/^(?:(1)\.[0-9])$/
```

The described problem seems to only happen if at least one brace expression is present in the pattern and it comes after the dot.

### LINKED ISSUE #125: Token output missing in `picomatch.parse` from logical or with empty element
1. Run `require('picomatch').parse('foo.(c|m|)js')`
2. Observer the following, where the `output` for the text token of `c|m|` is actually `|m|`

```js
{
  input: 'foo.(c|m|)js',
  index: 11,
  start: 0,
  dot: false,
  consumed: 'foo.(c|m|)js',
  output: 'foo\\.(c|m|)js', // < the output is what we would expect
  prefix: '',
  backtrack: false,
  negated: false,
  brackets: 0,
  braces: 0,
  parens: 0,
  quotes: 0,
  globstar: false,
  tokens: [
    { type: 'bos', value: '', output: '' },
    { type: 'text', value: 'foo.', prev: [Object], output: '.' },
    { type: 'paren', value: '(', prev: [Object] },
    { type: 'text', value: 'c|m|', prev: [Object], output: '|m|' }, // 'c' is missing from the output in this token
    { type: 'paren', value: ')', output: ')', prev: [Object] },
    { type: 'text', value: 'js', prev: [Object] }
  ],
  peek: [Function (anonymous)],
  advance: [Function (anonymous)]
}
```

If the logical expression is modified to remove the empty element, for example making it `c|m|x`, the the problem disappears.

### PR DESCRIPTION
**Pull request by connor4312**
Previously sibling `text` tokens would exclude the `output` from the first token, resulting in the referenced issues. I think this should be a fairly safe change.

Fixes #125
Fixes #100

### CODE REVIEW

File: test/api.picomatch.js [hunk 1]
```diff
@@ -345,6 +345,22 @@ describe('picomatch', () => {
 
         assertTokens(tokens, expected);
       });
+
+      it('pictomatch issue#125, issue#100', () => {
+        const { tokens } = picomatch.parse('foo.(m|c|)js');
+
+        const expected = [
+          ['bos', { output: '', value: '' }],
+          ['text', { output: 'foo.', value: 'foo.' }],
```
Comment (connor4312) [inline test/api.picomatch.js:354]: This was just a `.`, which is what issue #100 referenced

File: test/api.picomatch.js [hunk 2]
```diff
@@ -345,6 +345,22 @@ describe('picomatch', () => {
...
+          ['paren', { output: undefined, value: '(' }],
+          ['text', { output: 'm|c|', value: 'm|c|' }],
```
Comment (connor4312) [inline test/api.picomatch.js:356]: This was `|c|` which is what #125 referenced

**Comment by jonschlinkert** [comment]
Sorry for the late reply, and thanks for the PR. Reviewing now!
